use crate::prelude::*;
use crate::types::RiskAssessment;
use genpdf::Element;
use genpdf::{Alignment, Document, elements, fonts, style};
use std::path::PathBuf;

pub fn generate_pdf_report(
    filename: &PathBuf,
    assessment: &RiskAssessment,
    out_path: &str,
    graph_img_path: Option<&str>, // Optional plotters graph
) -> Result<()> {
    // 1. Initialize Document and Fonts
    let font_family = fonts::from_files("./assets/fonts", "LiberationSans", None)?;
    let mut doc = Document::new(font_family);
    doc.set_title(format!("BAT Report - {:?}", filename));

    let mut decorator = genpdf::SimplePageDecorator::new();
    decorator.set_margins(10);
    doc.set_page_decorator(decorator);

    // 2. Report Header
    doc.push(
        elements::Paragraph::new("Binary Analysis Tool (BAT) - Threat Intelligence Report")
            .aligned(Alignment::Center)
            .styled(style::Style::new().bold().with_font_size(18)),
    );
    doc.push(elements::Break::new(2));

    // 3. Executive Summary (BLUF)
    doc.push(
        elements::Paragraph::new("Executive Summary")
            .styled(style::Style::new().bold().with_font_size(14)),
    );
    doc.push(elements::Paragraph::new(format!(
        "Target File: {:?}",
        filename
    )));
    doc.push(elements::Paragraph::new(format!(
        "Final Verdict: {} (Score: {}/100)",
        assessment.severity, assessment.score
    )));
    doc.push(elements::Break::new(1));

    doc.push(elements::Paragraph::new("Recommendations:").styled(style::Style::new().bold()));
    for rec in &assessment.recommendations {
        doc.push(elements::BulletPoint::new(elements::Paragraph::new(
            rec.clone(),
        )));
    }
    doc.push(elements::Break::new(2));

    // 4. Entropy Visualizations (If generated by plotters)
    if let Some(img_path) = graph_img_path {
        doc.push(
            elements::Paragraph::new("Section Entropy Analysis")
                .styled(style::Style::new().bold().with_font_size(14)),
        );
        // doc.push(
        //     elements::Image::from_path(img_path).expect("Failed to load plotters graph image"),
        // );
        doc.push(elements::Break::new(2));
    }

    // 5. Technical Findings Table
    doc.push(
        elements::Paragraph::new("Technical Indicators of Compromise (IOCs)")
            .styled(style::Style::new().bold().with_font_size(14)),
    );
    doc.push(elements::Break::new(1));

    if assessment.findings.is_empty() {
        doc.push(elements::Paragraph::new(
            "No significant indicators detected.",
        ));
    } else {
        // Create a 3-column table: Indicator, Confidence, Description
        let mut table = elements::TableLayout::new(vec![2, 1, 4]); // Column width ratios
        table.set_cell_decorator(elements::FrameCellDecorator::new(true, true, true));

        // Table Headers
        let mut header_row = table.row();
        header_row
            .push_element(elements::Paragraph::new("Indicator").styled(style::Style::new().bold()));
        header_row.push_element(
            elements::Paragraph::new("Confidence").styled(style::Style::new().bold()),
        );
        header_row.push_element(
            elements::Paragraph::new("Description").styled(style::Style::new().bold()),
        );
        header_row.push().unwrap();

        // Table Rows
        for finding in &assessment.findings {
            let mut row = table.row();
            row.push_element(elements::Paragraph::new(finding.indicator.clone()));
            row.push_element(elements::Paragraph::new(format!(
                "{:?}",
                finding.confidence
            )));
            row.push_element(elements::Paragraph::new(finding.description.clone()));
            row.push().unwrap();
        }
        doc.push(table);
    }

    // 6. Finalize and Save
    doc.render_to_file(out_path)?;
    Ok(())
}
